### ISSUE TITLE
Config Problem

### ISSUE THREAD

**Issue by SideralisMusic** [barribob/bosses-of-mass-destruction#113]
I'm changing the values of hp in the config of this mod, and for some reason, I get no change at all, they stay the same, happens with other stats too such as armor

**Comment by miyo6032** [comment]
did you restart the client/server before testing

**Comment by SideralisMusic** [comment]
Yes I did

**Comment by miyo6032** [comment]
what version is the mod

**Comment by SideralisMusic** [comment]
1.7.4

**Comment by miyo6032** [comment]
are you editing the file or are you using mod menu

**Comment by SideralisMusic** [comment]
Sorry, been extremely busy past few months. Editing file. Modpack is prominence 2 rpg fabric but I believe I have same problem as well in mmc2 fabric

**Comment by miyo6032** [comment]
sorry, can't replicate on 1.8.2-1.20.4. if you can get a minimal setup to replicate let me know
