### ISSUE TITLE
Server lag caused by multipart entity lib

### ISSUE THREAD

**Issue by someaddons** [barribob/bosses-of-mass-destruction#120]
The multipart library you're including is causing lag:
![image](https://github.com/miyo6032/bosses-of-mass-destruction/assets/38401808/48ca108e-9b7f-4fa7-bc1b-63472867c022)

https://github.com/miyo6032/MultipartEntities/blob/master/src/main/java/io/github/stuff_stuffs/multipart_entities/mixin/common/MixinBox.java

This mixin causes a simple math operation to become expensive due to injecting into it which creates a new callback object on each invokation

**Comment by miyo6032** [comment]
can you send me the spark link - or how you got it to have the lag, can't produce it with a minimal setup
