### ISSUE TITLE
Boss armor value capped at 24

### ISSUE THREAD

**Issue by NolanHewitt** [barribob/bosses-of-mass-destruction#126]
Something seems to be wrong with the config for armor values. I have the void blossom set to 16 but it has 20 armor. I have the gauntlet set to 20 but its 24 in game. I tried setting the obsidilith to 40, but it also is set to 24 in game. Using the fabric version of the mod for minecraft version 1.20.1

**Comment by miyo6032** [comment]
the mod forces the bosses to have have high armor when not interacting with a survival player
