### ISSUE TITLE
config problem hp

### ISSUE THREAD

**Issue by FairyCat31** [barribob/bosses-of-mass-destruction#130]
I have discovered one problem with the config. When I increase the hp of bosses by more than 1024, it doesn't work in game.

For example, I set 2000 xp for the lich in the config file, but the mod actually set 1024 xp for the lich.
I changed the 2000 value to 4000 and got the same situation. In game, the mod sets 1024 xp for the lich.

Can you please solve this problem?

**Comment by barribob** [comment]
This is not a limit of the mod, but a limit of minecraft
